links:
  tracking_tools: /afs/cern.ch/eng/tracking-tools
  modules: tracking_tools/modules
  tools: tracking_tools/tools
  beambeam_macros: tracking_tools/beambeam_macros
  errors: tracking_tools/errors
  optics_repository: /afs/cern.ch/eng/lhc/optics
mode: b1_with_bb
optics_file: optics_repository/runIII/RunIII_dev/2022_V1/PROTON/opticsfile.29
check_betas_at_ips: true
check_separations_at_ips: true
save_intermediate_twiss: true
tol_beta:
- 0.001
- 0.1
- 0.001
- 0.01
tol_sep:
- 1.0e-06
- 1.0e-06
- 1.0e-06
- 1.0e-06
tol_co_flatness: 1.0e-06
beam_norm_emit_x: 2.5
beam_norm_emit_y: 2.5
beam_sigt: 0.076
beam_sige: 0.00011
beam_npart: 180000000000.0
beam_energy_tot: 7000
qx0: 62.313
qy0: 60.318
chromaticity_x: 15
chromaticity_y: 15
vrf_total: 12.0
oct_current: -350
enable_lumi_control: true
sep_plane_ip2: x
sep_plane_ip8: y
lumi_ip8: 2.0e+33
fullsep_in_sigmas_ip2: 5
nco_IP1: 2736
nco_IP2: 2250
nco_IP5: 2736
nco_IP8: 2376
beambeam_config:
  numberOfLRPerIRSide:
  - 25
  - 20
  - 25
  - 20
  bunch_spacing_buckets: 10
  numberOfHOSlices: 11
  bunch_num_particles: null
  bunch_particle_charge: null
  sigmaz_m: null
  z_crab_twiss: 0.0
match_q_dq_with_bb: false
enable_crabs: false
N_iter_coupling: 2
delta_cmr: 0.001
delta_cmi: 0.0
verbose_mad_parts: true
knob_names:
  sepknob_ip2_mm: on_sep2h
  sepknob_ip8_mm: on_sep8v
  qknob_1:
    lhcb1: dQx.b1_sq
    lhcb2: dQx.b2_sq
  qknob_2:
    lhcb1: dQy.b1_sq
    lhcb2: dQy.b2_sq
  chromknob_1:
    lhcb1: dQpx.b1_sq
    lhcb2: dQpx.b2_sq
  chromknob_2:
    lhcb1: dQpy.b1_sq
    lhcb2: dQpy.b2_sq
  cmrknob:
    lhcb1: CMRS.b1_sq
    lhcb2: CMRS.b2_sq
  cmiknob:
    lhcb1: CMIS.b1_sq
    lhcb2: CMIS.b2_sq
knob_settings:
  on_x1: 150
  on_sep1: 0
  on_x2h: 0
  on_x2v: 200
  on_sep2h: 1.0
  on_sep2v: 0
  on_x5: 150
  on_sep5: 0
  on_x8h: -250
  on_x8v: 0
  on_sep8h: 0.0
  on_sep8v: -1.0
  on_disp: 0
  on_alice_normalized: 1
  on_lhcb_normalized: 1
  on_sol_atlas: 0
  on_sol_cms: 0
  on_sol_alice: 0
enable_imperfections: false
enable_knob_synthesis: false
pars_for_imperfections: {}
pars_for_legacy_bb_macros:
  par_b_t_dist: 25.0
  par_n_inside_D1: 5
